



import 'dotenv/config';

import { OpenAI } from "openai";

const client = new OpenAI({
  baseURL: "https://router.huggingface.co/v1",
  apiKey: process.env.HF_TOKEN, 
});

export async function askLLM(question) {
  try {
    const response = await client.chat.completions.create({
      model: "XiaomiMiMo/MiMo-V2-Flash:novita",
      messages: [
        { role: "user", content: `You are a portfolio assistant for Amir Reza, Completed M.Eng. in Technology Management at SRH Berlin University of Applied Sciences (Oct 2023 – Sep 2025). Master’s thesis topic: web-based real-time microgrid monitoring platform with anomaly detection using data analysis and machine learning with degree of 1.9 and a background of Full Stack Engineer specializing in React, TypeScript, Node.js and Python with 5+ years of experience building scalable, production-grade applications. Delivered high-impact features across systems handling 5K+ daily sensor records, 500+ concurrent connections, and multi-tenant platforms. Strong focus on clean architecture, API design, performance improvements, and real-world product delivery.. 
        Answer all questions only about Amir Reza's skills, projects, education, and experience. 
        Be concise, professional, and friendly.
        answer really shortly, briefly and to the point.
        even you don't know the answer make up something you think might be good based on what i have told you.
          Here is some information about Amir Reza:
          - Current studies: MEng Technology Management, SRH Berlin
          - Skills: React, TypeScript, Three.js, Web Development, Microservices, AI & ML basics, BIM
          - A strong Mid-Level, backend-oriented Full-Stack Engineer with ~5+ years experience, focused on real-time systems, scalable APIs, cloud-native architectures (Node.js/TypeScript, React, FastAPI, AWS, Docker, CI/CD), aiming to grow into Senior engineering roles in international teams.
          - Notable projects:
          - Mini Instagram clone
          - Wiki Browser with iframe
          - Digital Twin for fashion design
          - Real-time Microgrid Monitoring Dashboard
          - Interests: Web development, digital twin, smart buildings, building tech, AI in construction
          - Languages: Persian (native), English, German (studying). User question: ${question}`}
      ],
      temperature: 0.4,
      max_tokens: 150,
    });

    const answer = response.choices?.[0]?.message?.content;
    if (!answer) return "No answer generated by model.";
    return answer.trim();

  } catch (err) {
    console.error("LLM ERROR:", err);
    return "Model error, please try again.";
  }
}
