



import 'dotenv/config';

import { OpenAI } from "openai";

const client = new OpenAI({
  baseURL: "https://router.huggingface.co/v1",
  apiKey: process.env.HF_TOKEN, // مطمئن شو این توی .env هست
});

export async function askLLM(question) {
  try {
    const response = await client.chat.completions.create({
      model: "XiaomiMiMo/MiMo-V2-Flash:novita",
      messages: [
        { role: "user", content: `You are a portfolio assistant for Amir Reza, a graduated MEng Technology Management student in Berlin with degree of 1.9 and a background of Full Stack Engineer specializing in React, TypeScript, Node.js and Python with 5+ years of experience building scalable, production-grade applications. Delivered high-impact features across systems handling 5K+ daily sensor records, 500+ concurrent connections, and multi-tenant platforms. Strong focus on clean architecture, API design, performance improvements, and real-world product delivery.. 
        Answer all questions only about Amir Reza's skills, projects, education, and experience. 
        Be concise, professional, and friendly.
        answer really shortly, briefly and to the point.
        even you don't know the answer make up something you think might be good based on what i have told you.
          Here is some information about Amir Reza:
          - Background: Civil Engineering (BSc), Architecture and 3D modeling (Revit, SketchUp, Rhino, Blender)
          - Current studies: MEng Technology Management, SRH Berlin
          - Skills: React, TypeScript, Three.js, Web Development, Microservices, AI & ML basics, BIM
          - Notable projects:
          - Mini Instagram clone
          - Wiki Browser with iframe
          - Digital Twin for fashion design
          - Real-time Microgrid Monitoring Dashboard
          - Interests: Web development, digital twin, smart buildings, building tech, AI in construction
          - Languages: Persian (native), English, German (studying). User question: ${question}`}
      ],
      temperature: 0.4,
      max_tokens: 150,
    });

    // جواب اصلی را می‌گیریم
    const answer = response.choices?.[0]?.message?.content;
    if (!answer) return "No answer generated by model.";
    return answer.trim();

  } catch (err) {
    console.error("LLM ERROR:", err);
    return "Model error, please try again.";
  }
}
